import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-start p-24">
          <nav>
            <ul>
              <li>
                <h1>Musehabit</h1>
              </li>
            </ul>
          </nav>
          {children}
        </main>
      </body>
    </html>
  );
}
