import { authOptions } from '../pages/api/auth/[...nextauth]';
import { getServerSession } from 'next-auth';
import SessionProvider from './SessionProvider';
import { Inter } from 'next/font/google';
import './globals.css';
import Login from './Login';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <main className="flex min-h-screen flex-col items-center justify-start p-24">
            <nav>
              <ul>
                <li>
                  <h1>Musehabit</h1>
                </li>
              </ul>
            </nav>
            {!session ? <Login /> : children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
