import { authOptions } from "../pages/api/auth/[...nextauth]";
import { getServerSession } from "next-auth";
import SessionProvider from "./SessionProvider";
import { Inter } from "next/font/google";
import "./globals.css";
import navData from "@/lib/navData";
import Login from "./Login";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <main className="flex min-h-screen flex-col items-center justify-start p-24">
            <nav>
              <ul>
                <li>
                  <Link href="/">
                    <h1>Musehabit</h1>
                  </Link>
                </li>
                {navData.map((navItem) => (
                  <li key={navItem.url}>
                    <Link href={navItem.url}>{navItem.text}</Link>
                  </li>
                ))}
              </ul>
            </nav>
            {!session ? <Login /> : children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
